/*
 * Copyright (c) 2026 LatentJam Project
 * SPDX-License-Identifier: Apache-2.0
 */
package io.github.nikitasud.latentjam.smart

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.toKString
import kotlinx.cinterop.usePinned
import platform.Foundation.NSData
import platform.Foundation.NSFileManager
import platform.Foundation.dataWithContentsOfFile
import platform.posix.getenv
import platform.posix.memcpy
import kotlin.math.abs
import kotlin.math.sqrt
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * The cross-platform gate on the audio encoder.
 *
 * An index built on one device is only meaningful on another if the encoder
 * agrees, so "it runs on iOS" is not the interesting claim — "it produces the
 * same vector" is. This runs the real model through the Kotlin/Native ORT
 * binding and compares against a reference generated by a different runtime
 * entirely (`tools/make_embedding_fixture.py`).
 *
 * Self-skips when the model or fixture is absent, matching Id3RealFileTest:
 * the 43 MB model is not in the repository.
 *
 *     SMART_AUDIO_MODEL=androidApp/src/main/assets/ml/mnv4_audio.onnx \
 *     SMART_EMBEDDING_FIXTURE=core/smart/src/commonTest/resources/embedding_fixture.bin \
 *     ./gradlew :core:smart:iosSimulatorArm64Test
 */
@OptIn(ExperimentalForeignApi::class)
class OrtEmbeddingParityTest {

    @Test
    fun `audio encoder reproduces the reference embedding`() {
        val modelPath = env("SMART_AUDIO_MODEL") ?: return skip("SMART_AUDIO_MODEL")
        val fixturePath = env("SMART_EMBEDDING_FIXTURE") ?: return skip("SMART_EMBEDDING_FIXTURE")
        if (!NSFileManager.defaultManager.fileExistsAtPath(modelPath)) return skip(modelPath)
        if (!NSFileManager.defaultManager.fileExistsAtPath(fixturePath)) return skip(fixturePath)

        val expected = readFixture(fixturePath)
        assertTrue(expected.size == EMBEDDING_DIM, "fixture has ${expected.size} floats")

        val session = Ort.createSession(modelPath)
        val actual = try {
            Ort.runFloat(
                session = session,
                inputName = "waveform",
                input = referenceWaveform(),
                inputShape = longArrayOf(1, SAMPLES.toLong()),
                outputName = "embedding",
                outputSize = EMBEDDING_DIM,
            )
        } finally {
            Ort.releaseSession(session)
        }

        // The model L2-normalises in-graph, so a norm far from 1 means the input
        // never reached it — a much more useful failure than a cosine of 0.3.
        val norm = sqrt(actual.fold(0.0) { acc, v -> acc + v.toDouble() * v })
        assertTrue(abs(norm - 1.0) < 1e-3, "embedding norm was $norm, expected ~1")

        val cosine = cosine(expected, actual)
        val maxDelta = expected.indices.maxOf { abs(expected[it] - actual[it]).toDouble() }
        // Reported on success too: a gate that only speaks when it fails cannot be
        // told apart from a gate that silently skipped.
        println(
            "ORT PARITY ran: norm=$norm cosine=$cosine maxDelta=$maxDelta " +
                "actual[0..3]=${actual.take(4)} expected[0..3]=${expected.take(4)}",
        )
        // Not bit-equality: the reference runtime and the device runtime are
        // different ONNX Runtime builds, and kernels are free to reassociate.
        // 0.9999 is tight enough that any real divergence — a wrong window, a
        // transposed shape, a dtype slip — fails it comfortably.
        assertTrue(cosine > 0.9999, "cosine $cosine, max element delta $maxDelta")
    }

    private fun cosine(a: FloatArray, b: FloatArray): Double {
        var dot = 0.0
        var na = 0.0
        var nb = 0.0
        for (i in a.indices) {
            dot += a[i].toDouble() * b[i]
            na += a[i].toDouble() * a[i]
            nb += b[i].toDouble() * b[i]
        }
        return dot / (sqrt(na) * sqrt(nb))
    }

    /**
     * Regenerates the fixture's input.
     *
     * An LCG, not a sine: integer arithmetic is bit-identical across Python,
     * the JVM and Kotlin/Native, so any difference in the output is the model's
     * rather than libm's.
     */
    private fun referenceWaveform(): FloatArray {
        val out = FloatArray(SAMPLES)
        var state = 12345L
        for (i in out.indices) {
            state = (state * 1103515245L + 12345L) and 0x7FFFFFFFL
            out[i] = (state.toDouble() / 2147483648.0 * 2.0 - 1.0).toFloat()
        }
        return out
    }

    /** `[dim:int32-le][dim × float32-le]`, as written by the generator. */
    private fun readFixture(path: String): FloatArray {
        val data = NSData.dataWithContentsOfFile(path) ?: return FloatArray(0)
        val bytes = ByteArray(data.length.toInt())
        if (bytes.isEmpty()) return FloatArray(0)
        bytes.usePinned { memcpy(it.addressOf(0), data.bytes, data.length) }
        val dim = (bytes[0].toInt() and 0xFF) or
            ((bytes[1].toInt() and 0xFF) shl 8) or
            ((bytes[2].toInt() and 0xFF) shl 16) or
            ((bytes[3].toInt() and 0xFF) shl 24)
        return FloatArray(dim) { index ->
            val at = 4 + index * 4
            val raw = (bytes[at].toInt() and 0xFF) or
                ((bytes[at + 1].toInt() and 0xFF) shl 8) or
                ((bytes[at + 2].toInt() and 0xFF) shl 16) or
                ((bytes[at + 3].toInt() and 0xFF) shl 24)
            Float.fromBits(raw)
        }
    }

    private fun env(name: String): String? = getenv(name)?.toKString()?.takeIf { it.isNotBlank() }

    private fun skip(what: String) {
        println("SKIP OrtEmbeddingParityTest: $what not available")
    }

    private companion object {
        const val SAMPLES = 320_000
        const val EMBEDDING_DIM = 960
    }
}
